### ISSUE TITLE
Google Dataproc API lab

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/hpa-labs#2]
Code the following operations with the Dataproc API:
- [X] Create clusters.
- [X] Submit jobs.
- [X] Delete clusters.
- [X] Upload code for jobs to Google Storage.
- [X] Run uploaded code.
- [X] Partitioning example: generate random numbers in partitions, partition by module, sort within partitions.
- [X] Run Spark job at Dataproc.
- [X] Get job output.
- [X] Monitor job status.
- [X] Rewrite wrapper to Ruby.
- [X] Run with user keys (1/2).
  - [X] Storage.
- [X] Operation timings.
  - [X] Bigger clusters.
  - [X] Bigger job.
- [X] Rewrite pointagg for dataproc.
  - [X] Use Google Storage.
  - [X] Adapt viewer for Google Storage.
  - [ ] Fix crashes
    - [X] OOM "fixed" by increasing `spark:spark.yarn.am.memoryOverhead` and `spark:spark.yarn.executor.memoryOverhead` to `'6000'`. Don't know whether it's a valid fix yet.
    - [X] Fix Hadoop job not finishing (despite Spark job does).
    - [X] Fix `ExecutorLostFailure .. Container exited with a non-zero exit code 143` error on big datasets.
    - [ ] [Spark ConcurrentModificationException bug](https://issues.apache.org/jira/browse/SPARK-17463) fixed in the next patch version.
- [X] Monitor CPU with [CPC](http://www.pcp.io/documentation.html) and [Vector](http://rhelblog.redhat.com/2015/12/18/getting-started-using-performance-co-pilot-and-vector-for-browser-based-metric-visualizations/).
- [ ] Issue: job finishing in Spark, not in Hadoop or Dataproc.
- [ ] Run with user keys (2/2).
  - [ ] Dataproc.
- [ ] Cluster of preemptive machines. How stable the master when preemptive instance is gone?

Nice-to-have:
- ~~Future-based SDK returning already completed long-running operations (such as make `createCluster` poll Google Dataproc and return on cluster creation ending).~~

**Comment by dkourilov** [comment]
We can consider Dataproc testing as finished, I've run a number of distributed join workloads on Dataproc/Spark 2.0.1 with Python3/Jupyter, and have not experienced any issues with OOM or random crashes. As we discussed briefly, your issues were likely caused by incorrect balance between partition size/available memory.
